name: "Generate CycloneDX SBOM (cdxgen)"

on:
  workflow_dispatch:
    inputs:
      sbom_filename:
        description: 'SBOM filename to create (relative to repo root)'
        required: false
        default: 'sbom.cdx.json'
      format:
        description: 'SBOM format: json or xml'
        required: false
        default: 'json'
      scan_path:
        description: 'Path to scan (relative to repo root)'
        required: false
        default: '.'
      extra_args:
        description: 'Extra CLI args to pass to cdxgen (optional)'
        required: false
        default: ''

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (use Node 20 to provide Web APIs required by undici)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install cdxgen (npm)
        run: |
          npm install -g @cyclonedx/cdxgen

      - name: Generate CycloneDX SBOM with cdxgen
        env:
          SBOM_FILE: ${{ inputs.sbom_filename }}
          FORMAT: ${{ inputs.format }}
          SCAN_PATH: ${{ inputs.scan_path }}
          EXTRA_ARGS: ${{ inputs.extra_args }}
        run: |
          set -euo pipefail
          echo "Generating SBOM: ${SBOM_FILE} (format=${FORMAT}) for path: ${SCAN_PATH}"
          mkdir -p "$(dirname "${SBOM_FILE}")" || true
          # cdxgen supports -o/--output and --format; redirect to file as fallback
          if cdxgen --help 2>&1 | grep -q -- '-o'; then
            cdxgen -o "${SBOM_FILE}" --format "${FORMAT}" ${EXTRA_ARGS} "${SCAN_PATH}"
          else
            cdxgen --format "${FORMAT}" ${EXTRA_ARGS} "${SCAN_PATH}" > "${SBOM_FILE}"
          fi
          echo "SBOM generated at: $(realpath "${SBOM_FILE}")"
          ls -la "${SBOM_FILE}" || true
          sha256sum "${SBOM_FILE}" || true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ${{ inputs.sbom_filename }}
